### ISSUE TITLE
Fix max_download_threads in cluster mode

### ISSUE THREAD

**Issue by leoisl** [karel-brinda/mof-search#227]
> max_download_threads argument is ignored - we can download as much as we want;

Great if it worked for you. But we should be careful not to behave as DOS attackers. Eg NCBI according to some people than temporarily blocks entire IP ranges corresponding to research clusters.

_Originally posted by @karel-brinda in https://github.com/karel-brinda/mof-search/issues/226#issuecomment-1589295727_

**Comment by karel-brinda** [comment]
I'm closing this as this is very highly relevant to #236 and the corresponding PR.

@leoisl Please feel free to reopen it if you don't think so.
