### ISSUE TITLE
Downloading is not working and `make test` fails

### ISSUE THREAD

**Issue by leoisl** [karel-brinda/mof-search#234]
Download of compressed assemblies and COBS indexes is not working, and then `make test` fails, as would any execution of the pipeline. You might have not experienced this issue as the files were already downloaded so the download rules were skipped. It is failing due to a redirection, any file requested redirects to another url, and what we download is actually a HTML file describing this redirection, e.g.:
```
$ cat asms/bacillus_anthracis__01.tar.xz 
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="/records/4602622/files/bacillus_anthracis__01.tar.xz">/records/4602622/files/bacillus_anthracis__01.tar.xz</a>. If not, click the link.
```

Adding the `-L` parameter to `curl` fixes this, and I am pushing a PR right after opening this issue to fix it.
I am also re-enabling the CI tests so we ensure `make test` works on each PR.

**Comment by karel-brinda** [comment]
Hi Leandro, thanks for reporting this issue! One question – when you experienced this, this Snakemake fail after it downloaded HTML? We must ensure that it's the download rule that fails in such a case.

**Comment by karel-brinda** [comment]
Did Zenodo changed urls and is now giving 301 or 302?

**Comment by leoisl** [comment]
> Hi Leandro, thanks for reporting this issue! One question – when you experienced this, this Snakemake fail after it downloaded HTML? We must ensure that it's the download rule that fails in such a case.

It did fail! So this is good! See this excerpt:
```
File cobs/actinobacillus_pleuropneumoniae__01.cobs_classic.xz is too small, likely corrupted
File cobs/bacillus_anthracis__01.cobs_classic.xz is too small, likely corrupted
File cobs/bacillus_anthracis__01.cobs_classic.xz is not a valid xz archive
File cobs/actinobacillus_pleuropneumoniae__01.cobs_classic.xz is not a valid xz archive
[Tue Nov 21 16:01:31 2023]
Error in rule download_cobs_batch:
    jobid: 6
    output: cobs/bacillus_anthracis__01.cobs_classic.xz
    shell:
        
        curl "https://zenodo.org/record/6845083/files/bacillus_anthracis__01.cobs_classic.xz"  > cobs/bacillus_anthracis__01.cobs_classic.xz
        scripts/test_xz.py cobs/bacillus_anthracis__01.cobs_classic.xz
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job download_cobs_batch since they might be corrupted:
cobs/bacillus_anthracis__01.cobs_classic.xz
[Tue Nov 21 16:01:31 2023]
Error in rule download_cobs_batch:
    jobid: 4
    output: cobs/actinobacillus_pleuropneumoniae__01.cobs_classic.xz
    shell:
        
        curl "https://zenodo.org/record/6845083/files/actinobacillus_pleuropneumoniae__01.cobs_classic.xz"  > cobs/actinobacillus_pleuropneumoniae__01.cobs_classic.xz
        scripts/test_xz.py cobs/actinobacillus_pleuropneumoniae__01.cobs_classic.xz
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job download_cobs_batch since they might be corrupted:
cobs/actinobacillus_pleuropneumoniae__01.cobs_classic.xz
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-11-21T160128.278236.snakemake.log
make: *** [Makefile:33: test] Error 1
```

> Did Zenodo changed urls and is now giving 301 or 302?

I don't actually know... all I know is that I added the `-L` to `curl` and it is working again...

**Comment by leoisl** [comment]
https://github.com/karel-brinda/mof-search/blob/main/scripts/test_xz.py checked the `.xz` files and errored out
