### ISSUE TITLE
Zenodo is blocking some downloads

### ISSUE THREAD

**Issue by leoisl** [karel-brinda/mof-search#236]
When running mof-search at the EBI cluster, most of the downloads succeed but some fail. Zenodo complains about me doing too many requests:
```
        <main id="main">
        <div class="invenio-page-body">
<div class="ui grid container error-page">
<div class="ui divider hidden"></div>
  <div class="row">
    <div class="column">
      
  <h1><i class="bolt icon"></i> Too many requests</h1>
  <p>You have made too many consecutive requests, please try again later.</p>

    </div>
  </div>
</div>

        </div>
        </main>
```

I think a quick fix around this is to reduce the default value of `max_download_threads` from 8 to 4, and to add `--restart-times 3` when running `snakemake` in `make download`. But this is just a quick fix, I think a proper fix would be, unfortunately, host somewhere else, as 8 concurrent downloads is not too much...

**Comment by iqbal-lab** [comment]
we could ask if we could add our data to EBI Biostudies
https://www.ebi.ac.uk/biostudies/
is apparently now the approved way, rather than ftp

**Comment by leoisl** [comment]
> we could ask if we could add our data to EBI Biostudies , and see if they can cope with higher requests before we bother https://www.ebi.ac.uk/biostudies/ is apparently now the approved way, rather than ftp

This seems like a proper solution, I'd be up for this.

In the mean time, the quick fix worked

**Comment by karel-brinda** [comment]
> When running mof-search at the EBI cluster, most of the downloads succeed but some fail.

> I think a quick fix around this is to reduce the default value of max_download_threads from 8 to 4, and to add --restart-times 3 when running snakemake in make download.

There's always a tradeoff in the style of

(1) "using maximal possible bandwidth" but "some jobs occasionally failing" (so needs to be executed eg twice),
vs.
(2) "not-using all bandwidth" (so more time needed) but "the pipeline not failing".

I usually prefer the first option among these two as I'm always struggling with  a limited bandwidth, but it's very much a question of personal taste (not sure what's the generally accepted guiding principle in the bioinfo community for this type of issues).

Some thoughts:
* I think the params should be set based on the time difference between (1) and (2) (if eg only 10%, then we should go with (2))
* The re-running of failed downloads can be done also on the level of Make (e.g., `make download` -> `make _download || make _download`)
* Isn't it possible to modify Snakemake parameters based on the number of attempt? If yes, we might try to progressively increase waiting times between starts of new downloads if they are failing.

(As Zenodo is so easy to use and we're likely to be using it, at least for some purposes, in the future as well, it would be good to find a good best-practice for this.)

**Comment by karel-brinda** [comment]
> we could ask if we could add our data to EBI Biostudies , and see if they can cope with higher requests before we bother
https://www.ebi.ac.uk/biostudies/
is apparently now the approved way, rather than ftp

It would be fantastic, especially if you could use this as another source (eg primary - EBI, secondary - Zenodo, configurable in the config)!

From what I've heard from various people, the download experience with Zenodo is very different for people in Europe and in the US, so heaving two independent "mirrors" would be great!

**Comment by leoisl** [comment]
> I think the params should be set based on the time difference between (1) and (2) (if eg only 10%, then we should go with (2))

I agree. I just realised also that my description for this issue was imprecise. I had to run `make download` 5 or 6 times to finally be able to download everything. The issue is that once Zenodo blocks the first download, it will very likely block most of the subsequent ones as the rule will fail very quickly and another one will be tried as soon as possible, and also fail. If in the first run we had a handful of downloads failing and just rerunning a second time would fix it, then I think there is no need to think about this. But my single experience here is that I had to rerun it several times to finally finish downloading. I can benchmark this more carefully with 8 and 16 parallel downloads if you want to get a detailed stats on how many are failing. I tried with 4 parallel downloads and it worked just fine.

> * The re-running of failed downloads can be done also on the level of Make (e.g., `make download` -> `make _download || make _download`)

Yes! But I'd prefer to do it on the snakemake level with `--restart-times n`. Do you have any preference to do it on the `make` level?

> * Isn't it possible to modify Snakemake parameters based on the number of attempt? If yes, we might try to progressively increase waiting times between starts of new downloads if they are failing.

I think so, as long as we have access to the `attempt` variable we should be able to, which I think we have... Should we try this approach?

**Comment by karel-brinda** [comment]
What about adding random sleep times before all curl requests? The length of the interval from which the random numbers are drawn would be increased with each new failed attempt.

This would help to prevent the situation that once Snakemake is executed, it submits many new requests at the same time, and at the same time might keep the number of download threads reasonably high. Maybe even using [0,1] secs might help for this?

I actually think this is not just an issue of Zenodo, but essentially any service with some protection against DoS attacks – if too many requests are submitted from one IP in a too short time, it will then block them automatically.

> Do you have any preference to do it on the make level?

I don't as long as `--restart-times` does the job.

**Comment by leoisl** [comment]
Ok, will do this.

I just retried running `make download` just to be sure this is still an issue, and to provide a better issue description. This is still an issue:
1. 1st `make download` managed to download 162 files:
```
162 of 611 steps (27%) done
```
At some point, Zenodo starts rejecting the downloads and the download rules error out. `snakemake` is run with `--keep-going`, so it still requests all downloads, but then Zenodo just rejects all of them.

2. 2nd `make download` managed to download 147 files more:
```
147 of 449 steps (33%) done
```

3. 3rd `make download` managed to download 66 files more:
```
66 of 302 steps (22%) done
```

I stopped here. So we need to run `make download` a lot of times to be able to download all the 610 files.

**Comment by leoisl** [comment]
Reducing the number of parallel downloads to 4 took me 75% of the way in a clean run:
```
460 of 611 steps (75%) done
```

Just when I reduced the number of parallel downloads to 2 is when I managed to download all 610 files without any issues.

I still don't understand if Zenodo limits on number of parallel downloads or rate limits downloads per minute or hour. I could not find anything about this on the web. I did find [limits on API requests](https://developers.zenodo.org/#rate-limiting), but these limits are way higher than what we need to download the mof data, so I think it is unrelated.

Anyway, even with more details about the situation, I think our idea to fix this does not change. I will list some options just for the sake of listing:
1. Add a random timeout between requests if Zenodo start blocking downloads;
2. Remove `max_download_threads` from `config.yaml` and force it to be a small number (e.g. 2 or 1). This way we ensure Zenodo does not block downloads in the pipeline;

Let's remember this is a one-off operation, like setting up a database, so there is no problem if it is a bit slow... but I think we are going ahead with option 1?

**Comment by leoisl** [comment]
I can also host all files in my dropbox as a backup, I have 1.5TB of space left, allocating 100 GB would not be an issue...

**Comment by karel-brinda** [comment]
Very interestingly, I have completely opposite experience – my Internet is often not great so I usually increase the number of download threads of MOF-Search, in order to maximize the use of the bandwidth. So we should somehow find a way how to make this work for both type of users – with great and less great connections.

> I still don't understand if Zenodo limits on number of parallel downloads or rate limits downloads per minute or hour.

Maybe some AI detecting common patterns of potential DoS attacks / people taking too much resources?

> 1. Add a random timeout between requests if Zenodo start blocking downloads;

Yes, this would be great!

> 2. Remove max_download_threads from config.yaml and force it to be a small number (e.g. 2 or 1). This way we ensure Zenodo does not block downloads in the pipeline;

I'm strongly against this as I usually use a high number of threads and often modify this param.

However, we can still make a note in the documentation about this, mentioning that in case Zenodo is blocking the requests, the number of threads should be reduced.

> Let's remember this is a one-off operation, like setting up a database, so there is no problem if it is a bit slow... but I think we are going ahead with option 1?

This is actually a critical operation. If the download doesn't finish soon or is too annoying for any reason, people won't bother any more.

>  I can also host all files in my dropbox as a backup, I have 1.5TB of space left, allocating 100 GB would not be an issue...

I think I was considering this too at some point, but turned out it didn't work very well (the same about Google Drive). They intentionally put barriers to prevent people use their services this way.

**Comment by leoisl** [comment]
> I think I was considering this too at some point, but turned out it didn't work very well (the same about Google Drive). They intentionally put barriers to prevent people use their services this way.

My plan from [dropbox docs](https://help.dropbox.com/share/banned-links) gives 1 TB of bandwidth and unlimited file downloads per day. 1 TB of bandwidth is not a lot, with MOF data being 96GB in size, only 10 users would be able to fully download the DB per day from dropbox, however I think is enough for a failover mechanism.

There is also EBI FTP, which we definitely have space to host 96GB and unlimited bandwidth.

I am mentioning these two options: dropbox and EBI FTP because it is **very easy** for me to get them up and running: it is basically creating a directory and moving data that I already have there. With 3 different hosts for download, I am sure these downloading issues would go away and we would not need any fancy retrying mechanism. As per the host orders, I would propose:
1. EBI FTP (unlimited bandwidth and parallel downloads);
2. Zenodo (unknown restrictions but should work fine as a failover mechanism for EBI FTP);
3. My personal dropbox (1 TB bandwidth per day - should work fine as a failover of a failover);

If downloading from the first host fails, we proceed to the next one and so on. For the amount of users mof-search might have, this should be more than enough. 

Please let me know if you are happy with this and I can proceed with the implementation.

**Comment by leoisl** [comment]
Another option as well is to simply `tar` a bunch of files so that we have something like 10 long downloads to be made instead of 610 small ones. Zenodo will probably be happy with this.

Also, Figshare is another host we can add as failover.

Any opinions on this @karel-brinda ?

**Comment by karel-brinda** [comment]
Could you just try the random waiting times, with increases based on the nb. of failed attempts in the current rule?

**Comment by karel-brinda** [comment]
Hi @leoisl , several quick points:
* I tested MOF-Search on several computers / clusters, including the Harvard O2 cluster. I haven't experienced this issue anywhere.
* This likely means, that the EBI cluster is just so much stronger and/or better connected to CERN, so the rate of requests / used bandwidth  is much higher. This suggests that just including the sleep times (and possibly complemented with a max download speed param for CURL, but I guess this won't be necessary) should be sufficient.
* At the same time, Zenodo apparently found out people are sometimes downloading too many files at once, and now they limit the max number of files per dataset to 100. So for future datasets, taring / merging archives or other repackaging steps might be necessary.

**Comment by leoisl** [comment]
Thanks for the update, I am testing this today in a branch, but I am not too worried now if you haven't found this issue in multiple clusters

**Comment by leoisl** [comment]
As a silly first test, I just added a random sleep between 1 and 60 seconds before running `curl` and all downloads succeeded without any issues. I will then proceed with implementing this timeout based on the attempt number.

**Comment by karel-brinda** [comment]
Also, would it be possible to add the max number of attempts and the waiting time parametrization to the config so that we/users can easily change it in the future?

Thanks again for this fix.

**Comment by leoisl** [comment]
> Hi Leandro, great that this worked. I think one last thing to this to be merged – would it be possible to somehow reduce the times? 60 secs is a lot.

Yes, to which value should I reduce to (that being the default)? Note that it is a random value between 1 and 60.

> Also, would it be possible to add the max number of attempts and the waiting time parametrization to the config so that we/users can easily change it in the future?

Ok!

**Comment by karel-brinda** [comment]
> Yes, to which value should I reduce to (that being the default)? Note that it is a random value between 1 and 60.

Yup, thus average 30 sec.

Could you just get it down by a factor of eg 10x and test if it still works on the cluster (I guess this should be sufficient)?
