### ISSUE TITLE
Decompressing COBS indexes takes way too much RAM

### ISSUE THREAD

**Issue by leoisl** [karel-brinda/mof-search#246]
For example, decompressing a 486MB cobs index (`escherichia_coli__19.cobs_classic.xz`) takes 1.5GB, whereas it should take <100 MB. This does not happen with the compressed assemblies - decompressing a 495MB compressed assembly (`dustbin__10.tar.xz`) takes only 66 MB.
This is due to the `xz` compression dictionary size, which I set to `1500MiB` when compressing these indexes 1 year ago. I've later realised that using a `1500MiB` dictionary size just slightly improves the archive size than using the default `64MiB` dictionary size, but it incurs a much higher RAM when doing the decompression. This was fixed [in this commit](https://github.com/leoisl/mof-cobs-build/commit/07c41c2e04f5946520c6e865ce2264f79663e258), but the new xz indexes were not generated and updated. So every time we have to decompress or stream COBS indexes, we use too much RAM. This mostly does not matter when running on HPCs, but matter a lot when running locally, where we are targeting a RAM usage below 12 GB...

Best time to fix this is now, just wondering if you agree that this is indeed a problem and should be fixed.

**Comment by karel-brinda** [comment]
As going below 12 GB isn't currently a priority, I'm putting it into the bag of future [#IDEAs](https://github.com/karel-brinda/mof-search/issues?q=label%3AIDEAS-FOR-THE-FUTURE+is%3Aclosed).
